### ISSUE TITLE
wlanapi traceback on Addon initialization

### ISSUE THREAD

**Issue by JessicaTegner** [kefaslungu/resourceMonitor#18]
Hi.

I am getting the following error in the NVDA log after installing the addon and starting nvda. This makes it impossible to use the addon.

````
Error initializing global plugin <class 'globalPlugins.resourceMonitor.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\jessi\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\__init__.py", line 278, in __init__
    wlanapi.WlanOpenHandle(wlanapi.CLIENT_VERSION_WINDOWS_VISTA_OR_LATER, None, byref(self._negotiated_version), byref(self._client_handle))
  File "C:\Users\jessi\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\wlanapi.py", line 116, in WlanOpenHandle
    return wlanapi.WlanOpenHandle(dwClientVersion, pReserved, pdwNegotiatedVersion, phClientHandle)
  File "C:\Users\jessi\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\wlanapi.py", line 108, in errcheck
    raise WinError(c_long(result).value)
OSError: [WinError 1062] The process hasn't been started.
`


Windows & NVDA information

* OS-Name	Microsoft Windows 11 Home
* Version	10.0.22621 Build 22621
* NVDA Version: 2023.1
* Resource Monitor Version: 23.05.1

**Comment by cyrmax** [comment]
Hello! I have the same issue. When i've updated Resource Monitor to the latest 23.05.1 for me it is now impossible to use the addon because of the following traceback on NVDA startup.

ERROR - globalPluginHandler.initialize (23:21:34.232) - MainThread (15684):
Error initializing global plugin <class 'globalPlugins.resourceMonitor.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\cyrmax\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\__init__.py", line 278, in __init__
    wlanapi.WlanOpenHandle(wlanapi.CLIENT_VERSION_WINDOWS_VISTA_OR_LATER, None, byref(self._negotiated_version), byref(self._client_handle))
  File "C:\Users\cyrmax\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\wlanapi.py", line 116, in WlanOpenHandle
    return wlanapi.WlanOpenHandle(dwClientVersion, pReserved, pdwNegotiatedVersion, phClientHandle)
  File "C:\Users\cyrmax\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\wlanapi.py", line 108, in errcheck
    raise WinError(c_long(result).value)
OSError: [WinError 1062] The service has not been started.
WARNING - winKernel.__getattr__ (23:21:34.364) - MainThread (15684):
winKernel.SYSTEM_POWER_STATUS is deprecated, use winAPI._powerTracking.SystemPowerStatus instead.

NVDA version: alpha-28326,62536a97 (2023.2.0.28326)
Windows version: Windows 11 Education, 22h2
Windows version as python platform.platform() outputs: Windows-10-10.0.22621-SP0

It is important to note, that my machine is not a laptop and does not have WLAN at all, so corresponding services may not be started.

**Comment by cyrmax** [comment]
Update: version 23.05 works without any errors on my machine.
So the problem is brought by most recent changes in 23.05.1.

**Comment by kefaslungu** [comment]
hi,
resourceMonitor 23.06 will fix the issues where machines without wlan are having issues using the addon.
