### ISSUE TITLE
Windows Server: WLAN service/DLL is unavailable, causing startup error

### ISSUE THREAD

**Issue by josephsl** [kefaslungu/resourceMonitor#22]
Hi,

On Windows Server operating system, when loading the add-on at startup, a traceback involving wlanapi DLL is raised, specifically, the included WLAN module wants to import wlanapi.dll but servers do not have this. One solution is catching this inside a flag and flatly telling the add-on that no wireless devices are available on server systems.

Thanks.

**Comment by josephsl** [comment]
Traceback:

ERROR - globalPluginHandler.listPlugins (05:46:43.900) - MainThread (5164):
Error importing global plugin resourceMonitor
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\__init__.py", line 23, in <module>
    from . import wlanapi
  File "C:\Users\Administrator\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\wlanapi.py", line 5, in <module>
    wlanapi = windll.wlanapi
  File "ctypes\__init__.pyc", line 434, in __getattr__
  File "ctypes\__init__.pyc", line 364, in __init__
OSError: [WinError 126] The specified module could not be found

**Comment by josephsl** [comment]
Resolved through a series of three commits that address wlanapi unavailability, setting window handle to None, and not definig WLAN properties.
