### ISSUE TITLE
Resource Monitor and Sound Manager Addons Conflict

### ISSUE THREAD

**Issue by dangero2000** [kefaslungu/resourceMonitor#36]
There seems to be an issue where both addons are using some of the same libraries, and somehow, they're conflicting with each other, which causes both addons to not load. Here is my log entry.

Error importing global plugin resourceMonitor
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Garrett Brown\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\__init__.py", line 22, in <module>
    import psutil
  File "C:\Users\Garrett Brown\AppData\Roaming\nvda\addons\soundmanager\globalPlugins\soundmanager\psutil\__init__.py", line 147, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\Garrett Brown\AppData\Roaming\nvda\addons\soundmanager\globalPlugins\soundmanager\psutil\_pswindows.py", line 17, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows' from partially initialized module 'psutil' (most likely due to a circular import) (C:\Users\Garrett Brown\AppData\Roaming\nvda\addons\soundmanager\globalPlugins\soundmanager\psutil\__init__.py)

I'm not sure which addon is causing the issue, but removing Sound Maniger fixed it.

**Comment by josephsl** [comment]
Hi,

Are you using NVDA 2024.1? If yes, ask Sound Manager add-on developers to release an updated version of this add-on as it is outright incompatible with NVDA 2024.1 and later (latest Sound Manager on the add-on store (2023.07.26) ships with Python 3.7 version of psutil (5.4.7) which will NOT load properly if you've got NVDA 2024.1 or later).

Thanks.

**Comment by dangero2000** [comment]
I believe I am. I will submit an issue when I get a chance. I knew that some addons would break in the latest NVDA version, but I wasn't aware that broken addons could cause other addons to break as well.

**Comment by josephsl** [comment]
Hi,

There is always a possibility that when an ad-on loads, it can do something to cause other add-ons to break.

Turns out Sound Manager has a new release compatible with 2024.1 - it is not available on the add-on store yet (looks like a reminder to add-ons community might be in order...).

Thanks.

**Comment by josephsl** [comment]
Hi,

I'm in favor of closing this as "needs external fix", specifically from Sound Manager add-on authors due to compatibility issues noted above.

Thanks.
